# -*- coding: utf-8 -*-
"""RME301- Project Code ( T1,2&3)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kuUiqPKX9Ez0oq2KdP5e-lag-g7o-mlU
"""

# This our RME301 Project code
# Names : Retaj Al jerwan and Nada Saeed
# IDs: 2231133203 and 2231171802
# This program controls the Codey Rocky robot when A , B & C buttons are pressed
# The start of the code :


import codey as cd
import rocky
import event as ev
import time

@ev.button_a_pressed
def presseda():  # Task 1 : color detection
    time.sleep(2) # the robot will detect the colors when we press A
    mysensor = rocky.color_ir_sensor
    checkit = mysensor.is_color
    if checkit('red'):
        cd.emotion.look_down()
        cd.led.show(255, 0, 0, 3)
        cd.display.show_image("red", time_s=5)
        cd.display.clear()
    elif checkit('green'):
        cd.emotion.look_down()
        cd.led.show(140, 255, 0, mysensor.get_red())
        cd.display.show("Green", wait=False)
        time.sleep(5)
        cd.display.clear()
    elif checkit('blue'):
        cd.emotion.look_down()
        cd.led.show(0, 33, 255, 3)
        cd.display.show("Blue", wait=False)
        time.sleep(5)
        cd.display.clear()
    elif checkit('yellow'):
        cd.emotion.look_down()
        cd.led.show(255, 233, 0, 3)
        cd.display.show("Yellow", wait=False)
        time.sleep(5)
        cd.display.clear()
    elif checkit('cyan'):
        cd.emotion.look_down()
        cd.led.show(0, 255, 255, 3)
        cd.display.show("Cyan", wait=False)
        time.sleep(5)
        cd.display.clear()
    elif checkit('purple'):
        cd.emotion.look_down()
        cd.led.show(255, 0, 182, 3)
        cd.display.show("Purple", wait=False)
        time.sleep(5)
        cd.display.clear()
    elif checkit('black'):
        cd.emotion.look_down()
        cd.led.show(0, 0, 0, 3)
        cd.display.show("Black", wait=False)
        time.sleep(5)
        cd.display.clear()
    elif checkit('white'):
        cd.led.show(255, 255, 255, 3)
        cd.display.show("White", wait=False)
        time.sleep(5)
        cd.display.clear()
    else:
        cd.display.show("error")
#******************************************

@ev.button_b_pressed   # Task 2 : avoiding obstacles
def pressedb():        # the robot will avoid the obstacles when we press B
    rocky.forward(50, 1)
    while True:
        if rocky.color_ir_sensor.is_obstacle_ahead():
            rocky.turn_left_by_degree(90)
            rocky.forward(50, 1)
            rocky.turn_right_by_degree(90)
            rocky.forward(50, 1)
        elif rocky.color_ir_sensor.is_obstacle_ahead():
            rocky.turn_left_by_degree(90)
            rocky.forward(50, 1)
        else:
            rocky.forward(50, 2)



 #*************************************************

@ev.button_c_pressed  # Task 3 : line following
def pressedc():       # the robot will follow the line when we press C
    while True:
        readsensor = rocky.color_ir_sensor
        if readsensor.is_color('white'):
            while not not readsensor.is_color('white'):
                rocky.turn_right_by_degree(2)
        else:
            while not readsensor.is_color('white'):
                rocky.turn_left_by_degree(2)
        rocky.forward(3, 0.4)